return {
    Jenkinsfile = { "npm-groovy-lint" },
    asm = { "asmfmt" },
    astro = { "prettier", "prettierd" },
    blade = { "blade-formatter" },
    brs = { "bsfmt" },
    bzl = { "buildifier" },
    c = { "clang-format", "uncrustify" },
    clj = { "joker" },
    clojure = { "cljstyle", "zprint" },
    cmake = { "cmake_format", "gersemi" },
    cpp = { "clang-format", "uncrustify" },
    crystal = { "crystal" },
    cs = { "clang-format", "csharpier", "uncrustify" },
    css = { "biome", "prettier", "prettierd", "stylelint" },
    cuda = { "clang-format" },
    cue = { "cue_fmt" },
    d = { "dfmt" },
    d2 = { "d2" },
    dart = { "dart_format" },
    django = { "djlint" },
    elixir = { "mix" },
    elm = { "elm_format" },
    epuppet = { "puppet-lint" },
    erlang = { "erlfmt" },
    eruby = { "erb_format", "htmlbeautifier" },
    fennel = { "fnlfmt" },
    fish = { "fish_indent" },
    fnl = { "fnlfmt" },
    fortran = { "findent", "fprettify" },
    fsharp = { "fantomas" },
    gd = { "gdformat" },
    gdscript = { "gdformat" },
    gdscript3 = { "gdformat" },
    gleam = { "gleam" },
    gn = { "gn" },
    go = { "gofmt", "gofumpt", "goimports", "goimports_reviser", "golines" },
    graphql = { "biome", "prettier", "prettierd" },
    groovy = { "npm-groovy-lint" },
    handlebars = { "prettier", "prettierd" },
    hcl = { "hcl", "packer_fmt", "terragrunt_hclfmt" },
    html = { "prettier", "prettierd", "rustywind" },
    htmlangular = { "prettier", "prettierd" },
    htmldjango = { "djlint" },
    java = {
        "clang-format",
        "google-java-format",
        "npm-groovy-lint",
        "uncrustify",
    },
    javascript = { "biome", "prettier", "prettierd", "rustywind" },
    javascriptreact = { "biome", "prettier", "prettierd", "rustywind" },
    jinja = { "sqlfmt" },
    ["jinja.html"] = { "djlint" },
    json = { "biome", "prettier", "prettierd" },
    jsonc = { "biome", "prettier", "prettierd" },
    just = { "just" },
    kotlin = { "ktlint" },
    less = { "prettier", "prettierd", "stylelint" },
    lua = { "stylua" },
    luau = { "stylua" },
    markdown = {
        "cbfmt",
        "markdownlint",
        "mdformat",
        "prettier",
        "prettierd",
    },
    ["markdown.mdx"] = { "prettier", "prettierd" },
    nim = { "nimpretty" },
    nix = { "alejandra", "nixfmt", "nixpkgs_fmt" },
    ocaml = { "ocamlformat" },
    org = { "cbfmt" },
    pgsql = { "pg_format" },
    php = { "phpcbf", "php_cs_fixer", "pretty-php" },
    proto = { "buf", "clang-format" },
    puppet = { "puppet-lint" },
    purescript = { "purs-tidy" },
    python = { "black", "isort", "pyink", "usort", "yapf" },
    r = { "styler" },
    rescript = { "rescript-format" },
    rmd = { "styler" },
    ruby = { "rubocop", "rubyfmt", "rufo" },
    rust = { "leptosfmt" },
    sass = { "stylelint" },
    scala = { "scalafmt" },
    scss = { "prettier", "prettierd", "stylelint" },
    sh = { "shellharden", "shfmt" },
    sml = { "smlfmt" },
    solidity = { "forge_fmt" },
    sql = { "pg_format", "sql_formatter", "sqlfluff", "sqlfmt" },
    svelte = { "prettier", "prettierd", "rustywind" },
    swift = { "swift_format", "swiftformat", "swiftlint" },
    systemverilog = { "verible" },
    terraform = { "tofu_fmt", "terraform_fmt" },
    ["terraform-vars"] = { "tofu_fmt", "terraform_fmt" },
    tf = { "tofu_fmt", "terraform_fmt" },
    typ = { "typstfmt", "typstyle" },
    typescript = { "biome", "prettier", "prettierd", "rustywind" },
    typescriptreact = { "biome", "prettier", "prettierd", "rustywind" },
    typst = { "typstfmt", "typstyle" },
    verilog = { "verible" },
    vue = { "prettier", "prettierd", "rustywind" },
    xml = { "xmllint" },
    yaml = { "prettier", "prettierd", "yamlfix", "yamlfmt" },
}
